#include <iostream>
#include <string>

int main() {
    // characters map
   std::string swgohMap = "<option value=\"\">\"\"</option>\n";
    //all character info as of 11/26/2023
    std::string characters[] = {
    "0-0-0",
    "50R-T",
    "Aayla Secura",
    "Admiral Ackbar",
    "Admiral Piett",
    "Admiral Raddus",
    "Admiral Trench",
    "Ahsoka Tano",
    "Ahsoka Tano (Fulcrum)",
    "Amilyn Holdo",
    "ARC Trooper",
    "Asajj Ventress",
    "Aurra Sing",
    "B1 Battle Droid",
    "B2 Super Battle Droid",
    "Barriss Offee",
    "Bastila Shan",
    "Bastila Shan (Fallen)",
    "Baze Malbus",
    "BB-8",
    "Ben Solo",
    "Biggs Darklighter",
    "Bistan",
    "Bo-Katan Kryze",
    "Boba Fett",
    "Boba Fett, Scion of Jango",
    "Bodhi Rook",
    "Bossk",
    "Boushh (Leia Organa)",
    "BT-1",
    "C-3PO",
    "Cad Bane",
    "Cal Kestis",
    "Canderous Ordo",
    "Captain Drogan",
    "Captain Han Solo",
    "Captain Phasma",
    "Captain Rex",
    "Cara Dune",
    "Carth Onasi",
    "Cassian Andor",
    "CC-2224 \"Cody\"",
    "Cere Junda",
    "Chewbacca",
    "Chief Chirpa",
    "Chief Nebit",
    "Chirrut Îmwe",
    "Chopper",
    "Clone Sergeant - Phase I",
    "Clone Wars Chewbacca",
    "Colonel Starck",
    "Commander Ahsoka Tano",
    "Commander Luke Skywalker",
    "Coruscant Underworld Police",
    "Count Dooku",
    "CT-21-0408 \"Echo\"",
    "CT-5555 \"Fives\"",
    "CT-7567 \"Rex\"",
    "Dark Trooper",
    "Dark Trooper Moff Gideon",
    "Darth Malak",
    "Darth Malgus",
    "Darth Maul",
    "Darth Nihilus",
    "Darth Revan",
    "Darth Sidious",
    "Darth Sion",
    "Darth Talon",
    "Darth Traya",
    "Darth Vader",
    "Dash Rendar",
    "Dathcha",
    "Death Trooper",
    "Dengar",
    "Director Krennic",
    "Doctor Aphra",
    "Droideka",
    "Echo",
    "Eeth Koth",
    "Eighth Brother",
    "Embo",
    "Emperor Palpatine",
    "Enfys Nest",
    "Ewok Elder",
    "Ewok Scout",
    "Ezra Bridger",
    "Fennec Shand",
    "Fifth Brother",
    "Finn",
    "First Order Executioner",
    "First Order Officer",
    "First Order SF TIE Pilot",
    "First Order Stormtrooper",
    "First Order TIE Pilot",
    "Gamorrean Guard",
    "Gar Saxon",
    "Garazeb \"Zeb\" Orrelios",
    "General Grievous",
    "General Hux",
    "General Kenobi",
    "General Skywalker",
    "General Veers",
    "Geonosian Brood Alpha",
    "Geonosian Soldier",
    "Geonosian Spy",
    "Grand Admiral Thrawn",
    "Grand Inquisitor",
    "Grand Master Yoda",
    "Grand Moff Tarkin",
    "Greedo",
    "Greef Karga",
    "Han Solo",
    "Hera Syndulla",
    "Hermit Yoda",
    "HK-47",
    "Hondo Ohnaka",
    "Hoth Rebel Scout",
    "Hoth Rebel Soldier",
    "Hunter",
    "Iden Versio",
    "IG-100 MagnaGuard",
    "IG-11",
    "IG-12 & Grogu",
    "IG-86 Sentinel Droid",
    "IG-88",
    "Ima-Gun Di",
    "Imperial Probe Droid",
    "Imperial Super Commando",
    "Jabba the Hutt",
    "Jango Fett",
    "Jawa",
    "Jawa Engineer",
    "Jawa Scavenger",
    "Jedi Consular",
    "Jedi Knight Anakin",
    "Jedi Knight Cal Kestis",
    "Jedi Knight Guardian",
    "Jedi Knight Luke Skywalker",
    "Jedi Knight Revan",
    "Jedi Master Kenobi",
    "Jedi Master Luke Skywalker",
    "Jolee Bindo",
    "Juhani",
    "Jyn Erso",
    "K-2SO",
    "Kanan Jarrus",
    "Ki-Adi-Mundi",
    "Kit Fisto",
    "Krrsantan",
    "Kuiil",
    "Kyle Katarn",
    "Kylo Ren",
    "Kylo Ren (Unmasked)",
    "L3-37",
    "Lando Calrissian",
    "Leia Organa",
    "Lobot",
    "Logray",
    "Lord Vader",
    "Luke Skywalker (Farmboy)",
    "Luminara Unduli",
    "Mace Windu",
    "Magmatrooper",
    "Mara Jade, The Emperor's Hand",
    "Maul",
    "Merrin",
    "Mission Vao",
    "Mob Enforcer",
    "Moff Gideon",
    "Mon Mothma",
    "Mother Talzin",
    "Nightsister Acolyte",
    "Nightsister Initiate",
    "Nightsister Spirit",
    "Nightsister Zombie",
    "Ninth Sister",
    "Nute Gunray",
    "Obi-Wan Kenobi (Old Ben)",
    "Old Daka",
    "Omega",
    "Padmé Amidala",
    "Pao",
    "Paploo",
    "Paz Vizsla",
    "Plo Koon",
    "Poe Dameron",
    "Poggle the Lesser",
    "Princess Kneesaa",
    "Princess Leia",
    "Qi'ra",
    "Qui-Gon Jinn",
    "R2-D2",
    "Range Trooper",
    "Rebel Officer Leia Organa",
    "Resistance Hero Finn",
    "Resistance Hero Poe",
    "Resistance Pilot",
    "Resistance Trooper",
    "Rey",
    "Rey (Jedi Training)",
    "Rey (Scavenger)",
    "Rose Tico",
    "Royal Guard",
    "Sabine Wren",
    "Sana Starros",
    "Savage Opress",
    "Saw Gerrera",
    "Scarif Rebel Pathfinder",
    "Scout Trooper",
    "Second Sister",
    "Seventh Sister",
    "Shaak Ti",
    "Shoretrooper",
    "Sith Assassin",
    "Sith Empire Trooper",
    "Sith Eternal Emperor",
    "Sith Marauder",
    "Sith Trooper",
    "Skiff Guard (Lando Calrissian)",
    "Snowtrooper",
    "Starkiller",
    "Stormtrooper",
    "Stormtrooper Han",
    "Sun Fac",
    "Supreme Leader Kylo Ren",
    "T3-M4",
    "Talia",
    "Tarfful",
    "Taron Malicos",
    "Tech",
    "Teebo",
    "The Armorer",
    "The Mandalorian",
    "The Mandalorian (Beskar Armor)",
    "Third Sister",
    "Threepio & Chewie",
    "TIE Fighter Pilot",
    "Tusken Chieftain",
    "Tusken Raider",
    "Tusken Shaman",
    "Tusken Warrior",
    "Ugnaught",
    "URoRRuR'R'R",
    "Vandor Chewbacca",
    "Veteran Smuggler Chewbacca",
    "Veteran Smuggler Han Solo",
    "Visas Marr",
    "Wampa",
    "Wat Tambor",
    "Wedge Antilles",
    "Wicket",
    "Wrecker",
    "Young Han Solo",
    "Young Lando Calrissian",
    "Zaalbar",
    "Zam Wesell",
    "Zorii Bliss"
    };
    
    std::string characterlocation[] ={//character locations
        "Dark Side Battles: 2-A (Hard)","Dark Side Battles: 3-E (Hard)",
        "Cantina Battles: 5-B, Fanatical Devotion,Guild Activity Store",
        "Fleet Arena Store,Guild Events Store,Rebel Roundup,Squad Arena Store",
        "Light Side Battles: 6-B (Hard)","Dark Side Battles: 4-A (Hard)",
        "Conquest,Conquest Store",
        "Bronzium Data Card,Cantina Battles Store,Fleet Arena Store,Light Side Battles: 1-B (Hard),Places of Power",
        "Fanatical Devotion,Fleet Arena Store,Galactic Bounties II","Dark Side Battles: 7-C (Hard),Galactic Bounties II",
        "Cantina Battles: 5-G","Squad Arena Store","Cantina Battles: 7-C","Fleet Battles: 5-B (Hard)",
        "Cantina Battles: 6-D,Guild Activity Store",
        "Bronzium Data Card,Dark Side Battles: 5-C (Hard),Fanatical Devotion,Guild Activity Store",
        "Dark Side Battles: 5-B (Hard)","Dark Side Battles: 7-A (Hard)","Light Side Battles: 9-C (Hard),Rebel Roundup",
        "Journey Guide: Pieces and Plans","Conquest Store",
        "Bronzium Data Card,Cantina Battles: 3-G,Fleet Arena Store,Galactic War Store,Guild Events Store,Rebel Roundup",
        "Cantina Battles Store,Fleet Arena Store,Guild Events Store","Dark Side Battles: 6-D (Hard)",
        "Bronzium Data Card,Cantina Battles Store,Dark Side Battles: 2-B (Hard),Fleet Arena Store",
        "Guild Events Store,Proving Grounds",
        "Galactic War Store","Dark Side Battles: 9-B (Hard)","Dark Side Battles: 2-C (Hard)",
        "Light Side Battles: 2-C (Hard)","Journey Guide: Contact Protocol","Galactic War Store","Cantina Battles: 1-F",
        "Cantina Battles: 5-C","Cantina Battles: 6-F","Cantina Battles: 7-D, Rebel Roundup","Galactic War Store",
        "Dark Side Battles: 3-F (Hard)","Dark Side Battles: 5-E (Hard)","Cantina Battles: 8-E",
        "Guild Events Store,Rebel Roundup,Squad Arena Store","Fleet Arena Store, Guild Activity Store",
        "Light Side Battles: 3-A (Hard)","Journey Guide: One Famous Wookiee","Cantina Battles: 5-D, Forest Moon",
        "Squad Arena Store","Fleet Arena Store, Rebel Roundup","Cantina Battles Store,Guild Events Store,Rebel Roundup",
        "Bronzium Data Card,Fleet Arena Store,Guild Activity Store,Light Side Battles: 5-C (Hard),Places of Power",
        "Bronzium Data Card, Cantina Battles: 2-F","Guild Activity Store","Guild Events Store,Proving Grounds",
        "Journey Guide: Luke Skywalker Hero's Journey","Squad Arena Store",
        "Bronzium Data Card,Fleet Arena Store,Guild Activity Store,Light Side Battles: 5-C (Hard),Places of Power",
        "Fleet Arena Store, Guild Activity Store",
        "Bronzium Data Card,Cantina Battles Store,Dark Side Battles: 2-D (Hard),Fleet Arena Store,Places of Power",
        "Fleet Arena Store,Guild Activity Store,Places of Power","Light Side Battles: 1-C (Hard)","Conquest",
        "Journey Guide: Star Forge Showdown, Guild Events Store,","Conquest Store, Proving Grounds",
        "Fleet Arena Store, Guild Activity Store","Dark Side Battles: 9-A (Hard), Secrets and Shadows",
        "Journey Guide: Scourge of the Old Republic","Secrets and Shadows, Squad Arena Store","Light Side Battles: 9-A (Hard)",
        "Cantina Battles: 7-G","Hyperdrive Bundle, The Sith Triumvirate, Guild Store",
        "Fleet Arena Store,Hyperdrive Bundle,Military Might, Achievements","Cantina Battles: 7-E",
        "Bronzium Data Card,Galactic War Store,Light Side Battles: 3-F (Hard)","Cantina Battles: 8-A, Military Might",
        "Guild Activity Store","Guild Events Store,Light Side Battles: 9-D (Hard),Military Might","Journey Guide: Rogue Archaeologist",
        "Light Side Battles: 8-B (Hard)","Light Side Battles: 7-D (Hard)","Squad Arena Store","Light Side Battles: 6-E (Hard)",
        "Dark Side Battles: 8-C (Hard)","Journey Guide: Emperor's Demise","Fleet Battles: 5-D (Hard),Galactic Bounties II",
        "Bronzium Data Card,Forest Moon,Guild Activity Store,Light Side Battles: 2-A (Hard)",
        "Bronzium Data Card,Forest Moon,Light Side Battles: 2-A (Hard)",
        "Cantina Battles: 2-B,Fanatical Devotion,Fleet Arena Store,Guild Events Store,Rebel Roundup","Light Side Battles: 6-C (Hard)",
        "Cantina Battles: 4-A","Cantina Battles: 3-E,Guild Activity Store","Cantina Battles: 2-G","Cantina Battles Store",
        "Guild Activity Store","Light Side Battles: 2-B (Hard)","Dark Side Battles: 6-B (Hard),Fleet Arena Store",
        "Guild Activity Store","Cantina Battles: 2-E,Guild Events Store,Military Might",
        "Galactic War Store,Guild Events Store,Rebel Roundup","Fleet Arena Store,Ground War,Shard Store","Dark Side Battles: 6-A (Hard)",
        "Fanatical Devotion,Hyperdrive Bundle,Tank Takedown,Guild Store","Journey Guide: Clash on Kamino,Guild Events Store",
        "Bronzium Data Card,Guild Events Store,Light Side Battles: 4-C (Hard),Military Might","Cantina Battles: 8-D",
        "Cantina Battles: 1-A,Fleet Arena Store,Ground War","Cantina Battles: 4-D,Fleet Arena Store,Ground War",
        "Journey Guide: Artist of War","Journey Guide: Dark Times","Journey Guide: Grand Master's Training",
        "Fleet Arena Store,Guild Events Store,Squad Arena Store","Squad Arena Store",
        "Fleet Battles: 4-C (Hard),Light Side Battles: 3-E (Hard)","Galactic Bounties I,Hyperdrive Bundle,The Pit,Guild Store",
        "Guild Events Store,Light Side Battles: 2-F (Hard),Rebel Roundup","Fanatical Devotion,Guild Events Store",
        "Squad Arena Store","Cantina Battles: 1-D",
        "Bronzium Data Card,Cantina Battles Store,Dark Side Battles: 6-A (Hard),Guild Events Store,Rebel Roundup",
        "Bronzium Data Card,Dark Side Battles: 3-B (Hard),Guild Events Store,Rebel Roundup","Light Side Battles: 5-B (Hard)",
        "Light Side Battles: 4-D (Hard)","Bronzium Data Card,Cantina Battles: 3-C,Dark Side Battles: 6-E (Hard),Guild Activity Store",
        "Light Side Battles: 3-E (Hard)","N/A","Bronzium Data Card,Dark Side Battles: 2-F (Hard),Galactic War Store","Squad Arena Store",
        "Bronzium Data Card,Dark Side Battles: 5-C (Hard),Guild Activity Store",
        "Galactic Bounties I,Guild Events Store,Hoth Imperial Retaliation","Fleet Battles: 4-A (Hard),Guild Events Store,Military Might",
        "Greetings, Exalted One","Light Side Battles: 8-D (Hard)","Bronzium Data Card,Dark Side Battles: 4-F (Hard)",
        "Guild Activity Store","Cantina Battles Store",
        "Bronzium Data Card,Cantina Battles: 3-A,Dark Side Battles: 1-D (Hard),Fleet Arena Store,Places of Power",
        "Dark Side Battles: 1-B (Hard)","Journey Guide: Jedi Knight Cal Kestis ",
        "Bronzium Data Card,Cantina Battles Store,Dark Side Battles: 3-F (Hard)","Journey Guide: Luke Skywalker The Journey Continues",
        "Journey Guide: Legend of the Old Republic","What Must Be Done","The Journey's End","Dark Side Battles: 6-D (Hard)",
        "Light Side Battles: 6-A (Hard)","Guild Activity Store,Rebel Roundup","Galactic War Store,Guild Events Store,Rebel Roundup",
        "Fanatical Devotion,Guild Events Store,Rebel Roundup,Squad Arena Store","Geonosis Republic Offensive,Guild Events Store",
        "Cantina Battles: 4-F,Fanatical Devotion,Guild Activity Store","Cantina Battles: 7-A","Dark Side Battles: 5-A (Hard)",
        "Cantina Battles: 6-A","Cantina Battles: 4-C,Guild Activity Store","Cantina Battles: 3-F,Light Side Battles: 1-D (Hard)",
        "Cantina Battles: 5-A","Cantina Battles: 1-E,Guild Events Store,Rebel Roundup","Galactic Legend",
        "Bronzium Data Card,Light Side Battles: 4-B (Hard),Rebel Roundup","Forest Moon,Guild Activity Store",
        "Lord Vader Hero's Fall",
        "Cantina Battles: 1-B,Guild Activity Store,Guild Events Store,Light Side Battles: 7-D (Hard),Rebel Roundup",
        "Bronzium Data Card,Dark Side Battles: 2-E (Hard),Fanatical Devotion,Galactic War Store",
        "Bronzium Data Card,Fanatical Devotion,Fleet Arena Store,Light Side Battles: 2-E (Hard),Squad Arena Store",
        "Galactic War Store,Guild Events Store,Military Might","Light Side Battles: 6-D (Hard)","Guild Events Store,Proving Grounds",
        "Fleet Battles: 1-C (Hard)","Light Side Battles: 5-D (Hard)","Cantina Battles Store",
        "Cantina Battles: 4-E,Light Side Battles: 2-D (Hard)","Light Side Battles: 5-E (Hard)",
        "Defense of Dathomir,Light Side Battles: 8-A (Hard)","Cantina Battles: 2-A,Guild Activity Store","Galactic War Store",
        "Cantina Battles: 7-F,Ghosts of Dathomir","Dark Side Battles: 8-D (Hard),Ghosts of Dathomir","Light Side Battles: 3-D (Hard)",
        "Ground War,Squad Arena Store","Cantina Battles: 1-C,Guild Activity Store,Rebel Roundup",
        "Bronzium Data Card,Cantina Battles Store,Dark Side Battles: 4-B (Hard)","Fleet Battles: 4-D (Hard)",
        "Journey Guide: Aggressive Negotiations","Cantina Battles Store",
        "Cantina Battles: 3-D,Forest Moon,Galactic Bounties I,Guild Activity Store","N/A",
        "Bronzium Data Card,Cantina Battles: 4-G,Fleet Arena Store,Places of Power",
        "Cantina Battles Store,Fleet Arena Store,Light Side Battles: 7-B (Hard)",
        "Bronzium Data Card,Galactic War Store,Ground War,Light Side Battles: 4-E (Hard)","N/A",
        "Guild Events Store,Rebel Roundup,Squad Arena Store","Cantina Battles: 3-B,Galactic Bounties II",
        "Cantina Battles Store","Journey Guide: Daring Droid","Dark Side Battles: 3-A (Hard)",
        "Galactic Bounties I,Guild Events Store,Hoth Rebel Assault","Light Side Battles: 8-C (Hard)",
        "Light Side Battles: 6-B (Hard)","Fleet Arena Store,Galactic War Store","Guild Activity Store,Light Side Battles: 3-A (Hard)",
        "Heir to the Light Side","Journey Guide: Rey Hero's Journey",
        "Dark Side Battles: 5-D (Hard),Guild Activity Store,Light Side Battles: 1-A (Hard)",
        "Light Side Battles: 4-F (Hard)","Bronzium Data Card,Dark Side Battles: 5-F (Hard),Guild Events Store",
        "Dark Side Battles: 1-A (Hard),Rebel Roundup","Cantina Battles: 2-C","Squad Arena Store",
        "Light Side Battles: 4-B (Hard)","Fleet Arena Store,Fleet Battles: 2-C (Hard),Guild Events Store,Rebel Roundup",
        "Fleet Battles: 5-C (Hard)","Dark Side Battles: 4-C (Hard)","Dark Side Battles: 4-E (Hard)",
        "Fanatical Devotion,Fleet Battles: 5-A (Hard)","Light Side Battles: 9-B (Hard),Military Might",
        "Cantina Battles: 6-C,Guild Activity Store,Secrets and Shadows","Cantina Battles: 8-B,Secrets and Shadows",
        "The Final Order","Cantina Battles: 6-E","Light Side Battles: 2-B (Hard)","Light Side Battles: 3-B (Hard)",
        "Bronzium Data Card,Cantina Battles: 7-B,Guild Activity Store,Guild Events Store,Light Side Battles: 8-C (Hard),Military Might",
        "Journey Guide: The Force Unleashed",
        "Bronzium Data Card,Cantina Battles Store,Guild Events Store,Light Side Battles: 3-C (Hard),Military Might",
        "Cantina Battles Store,Guild Events Store,Rebel Roundup","Fleet Arena Store,Ground War,Guild Activity Store",
        "Heir to the Dark Side","Cantina Battles: 6-B",
        "Bronzium Data Card,Cantina Battles: 1-G,Dark Side Battles: 9-C (Hard),Guild Activity Store",
        "Dark Side Battles: 4-D (Hard)","Conquest","Light Side Battles: 5-F (Hard)",
        "Bronzium Data Card,Dark Side Battles: 3-D (Hard),Forest Moon,Galactic War Store,Light Side Battles: 4-A (Hard)",
        "Light Side Battles: 9-C (Hard)","Dark Side Battles: 3-C (Hard),Fleet Battles: 5-E (Hard)",
        "Journey Guide: The Mandalorian Hero's Journey","Rise of the Empire","Light Side Battles: 7-A (Hard)",
        "Cantina Battles: 4-B,Fleet Arena Store,Guild Events Store,Military Might","Dark Side Battles: 6-C (Hard)",
        "Bronzium Data Card, Dark Side Battles: 6-C (Hard), Galactic War Store","Fleet Arena Store, Guild Activity Store",
        "Cantina Battles: 2-D","Squad Arena Store","Bronzium Data Card Light Side Battles: 5-A (Hard)","Dark Side Battles: 4-D (Hard)",
        "Cantina Battles: 5-F","Cantina Battles: 5-E",
        "Dark Side Battles: 7-B (Hard) Galactic Bounties II","Galactic Bounties I, Guild Events Store",
        "Geonosis Separatist Might, Guild Events Store","Cantina Battles: 6-F, Fleet Arena ,Store Rebel Roundup",
        "Dark Side Battles: 8-A (Hard), Endor Escalation","Light Side Battles: 7-C (Hard)","Guild Activity Store",
        "Fleet Battles: 1-D (Hard)","Light Side Battles: 5-D (Hard)","Fleet Arena Store,Guild Activity Store",
        "Dark Side Battles: 1-C (Hard)"
    };

    int charcterdnodeamt[] = {//node amounts
    1,1,1,0,1,1,0,1,0,1,
    1,0,1,1,1,1,1,1,1,0,
    0,1,0,1,1,0,0,1,1,1,
    0,0,1,1,1,1,0,1,1,1,
    0,0,1,0,1,0,0,0,1,1,
    0,0,0,0,1,0,1,0,1,0,
    0,0,0,1,0,0,1,1,0,0,
    1,1,1,0,1,0,1,1,0,1,
    1,0,1,1,1,1,1,1,1,1,
    0,0,1,1,0,1,0,0,1,0,
    0,1,1,1,1,0,0,0,0,0,
    2,0,1,0,0,1,1,1,1,1,
    1,1,0,1,0,1,0,1,0,1,
    1,0,0,1,1,0,1,0,0,0,
    0,1,1,0,0,0,0,1,1,1,
    1,1,2,1,1,0,1,0,0,2,
    1,1,0,1,0,1,1,0,2,1,
    1,1,0,1,1,1,0,1,1,1,
    0,0,1,0,1,1,1,0,0,1,
    0,0,1,0,1,1,0,1,0,0,
    2,1,1,1,1,0,1,1,1,1,
    1,1,1,1,1,0,1,1,1,1,
    0,1,0,0,0,1,2,1,0,1,
    2,1,2,0,0,1,1,1,1,0,
    1,0,1,1,1,1,1,0,0,1,
    1,1,0,1,1,0,1
    };
    
    int charctershardamt[] = {//node shard amounts
    1,2,2,0,2,2,0,2,0,2,
    2,0,2,2,2,2,2,2,2,0,
    0,2,0,2,2,0,0,2,2,2,
    0,0,1,2,1,2,0,1,2,2,
    0,0,1,0,2,0,0,0,2,2,
    0,0,0,0,2,0,2,0,2,0,
    0,0,0,2,0,0,2,2,0,0,
    2,2,2,0,2,0,2,2,0,2,
    2,0,2,2,2,2,2,2,2,2,
    0,0,2,2,0,2,0,0,2,0,
    0,2,2,2,2,0,0,0,0,0,
    2,0,2,0,0,2,2,2,2,2,
    2,2,0,2,0,2,0,2,0,2,
    2,0,0,2,2,0,2,0,0,0,
    0,2,2,0,0,0,0,2,2,2,
    2,2,2,2,2,0,2,0,0,2,
    2,2,0,2,0,1,2,0,2,2,
    2,2,0,2,2,2,0,2,2,2,
    0,0,2,0,2,2,2,0,0,2,
    0,0,2,0,2,2,0,2,0,0,
    2,2,2,2,2,0,1,2,1,2,
    2,2,2,2,2,0,2,2,2,2,
    0,2,0,0,0,2,2,2,0,2,
    2,2,2,0,0,2,2,2,2,0,
    2,0,2,2,2,2,2,0,0,2,
    2,2,0,2,2,0,2
    };
    
    int shipshardamt[] = {//shard amounts in shipments
        0,0,5,5,0,0,0,5,5,0,
        0,5,0,0,5,5,0,0,0,0,
        0,5,5,0,5,0,0,0,0,0,
        0,5,0,0,0,5,5,0,0,0,
        5,5,0,0,0,5,5,5,5,0,
        5,0,0,5,0,5,5,5,0,0,
        0,0,5,0,0,5,0,0,5,5,
        0,5,0,5,5,0,0,0,5,0,
        0,0,0,5,0,5,0,0,5,0,
        5,5,0,5,5,5,5,5,0,5,
        0,5,0,5,5,0,0,0,0,0,
        0,5,5,5,5,0,5,5,0,0,
        5,0,0,5,5,5,5,5,0,0,
        0,5,5,5,0,0,5,0,0,0,
        0,0,0,5,5,5,5,5,0,0,
        0,5,0,0,5,0,0,5,0,5,
        5,5,5,0,0,0,0,5,0,0,
        0,5,5,0,0,0,5,5,5,0,
        0,5,5,0,5,5,5,0,5,0,
        5,0,0,5,0,0,5,5,0,0,
        5,0,5,0,0,5,0,5,0,0,
        0,0,0,5,0,0,0,0,0,5,
        0,5,5,10,0,0,5,0,0,0
        ,5,0,0,0,0,0,5,0,5,5
        ,0,5,0,0,0,0,0,5,5,5
        ,0,0,5,0,0,5,0
    };


//ships DAtA
    std::string ships[]={
"Ahsoka Tano's Jedi Starfighter","Anakin's Eta-2 Starfighter","B-28 Extinction-class Bomber","Biggs Darklighter's X-wing","Bistan's U-wing",
"BTL-B Y-wing Starfighter","Cassian's U-wing","Chimaera","Clone Sergeant's ARC-170","Ebon Hawk","Emperor's Shuttle","Endurance","Executor","Executrix",
"Finalizer","First Order SF TIE Fighter","First Order TIE Fighter","Fury-class Interceptor",
"Gauntlet Starfighter","Geonosian Soldier's Starfighter","Geonosian Spy's Starfighter","Ghost",
"Han's Millennium Falcon","Home One","Hound's Tooth","Hyena Bomber",
"IG-2000","Imperial TIE Bomber","Imperial TIE Fighter","Jedi Consular's Starfighter","Kylo Ren's Command Shuttle",
"Lando's Millennium Falcon","Leviathan","Malevolence","Marauder","Mark VI Interceptor","MG-100 StarFortress SF-17",
"Negotiator","Outrider","Phantom II","Plo Koon's Jedi Starfighter","Poe Dameron's X-wing","Profundity",
"Raddus","Raven's Claw","Razor Crest","Rebel Y-wing","Resistance X-wing","Rex's ARC-170","Rey's Millennium Falcon",
"Scimitar","Scythe","Sith Fighter","Slave I","Sun Fac's Geonosian Starfighter",
"TIE Advanced x1","TIE Dagger","TIE Defender","TIE Echelon","TIE Reaper","TIE Silencer","TIE/IN Interceptor Prototype",
"Umbaran Starfighter","Vulture Droid","Wedge Antilles's X-wing","Xanadu Blood"
    };
    std::string shiplocation[]{
"Galactic War Store","Fleet Battles: 1-B (Hard)","Light Side Battles: 6-C (Hard)","Galactic War Store","Fleet Arena Store","Light Side Battles: 7-C (Hard)",
"Cantina Battles Store","Imperial Chimaera","Galactic War Store","Cantina Battles: 8-E","Dark Side Battles: 7-D (Hard)","Capital Ship Upgrades - Mace Windu",
"Discarded Doctrine","Capital Ship Upgrades - Grand Moff Tarkin","General's Command","Guild Activity Store","Galactic War Store","Conquest","Fleet Arena Store",
"Galactic War Store","Galactic War Store","Fleet Arena Store","Flight of the Falcon","Capital Ship Upgrades - Admiral Ackbar","Light Side Battles: 8-D (Hard)",
"Dark Side Battles: 8-B (Hard)","Light Side Battles: 6-E (Hard)","Dark Side Battles: 5-A (Hard)","Galactic War Store","Galactic War Store",
"Light Side Battles: 9-A (Hard)","Fleet Battles: 1-D (Hard)","Journey Guide","Guild Events Store","n/a","n/a","Fleet Battles: 2-D (Hard)",
"Guild Events Store","Fleet Battles: 3-C (Hard)","Fleet Arena Store","Galactic War Store","Fleet Arena Store","Stardust Transmission",
"Admiral's Maneuver","Fleet Battles: 2-E (Hard)","Fleet Arena Store","Fleet Battles: 4-C (Hard)","Galactic War Store","Fleet Arena Store",
"Dark Side Battles: 5-D (Hard)","Fleet Arena Store","Conquest Store","Fleet Battles: 3-E (Hard)","Fleet Arena Store","Galactic War Store",
"Fleet Arena Store","n/a","Fleet Battles: 3-B (Hard)","Fleet Battles: 4-E (Hard)","Light Side Battles: 9-B (Hard)","Cantina Battles: 3-F","Proving Grounds",
"Galactic War Store","Light Side Battles: 4-D (Hard)","Galactic War Store","Light Side Battles: 8-B (Hard)"
    };
    int shipnodeamt[]={
0,1,1,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0
,0,0,0,0,1,1,1,1,0,0,1,1,0,0,0,0,1,0,1,
0,0,0,0,0,1,0,1,0,0,1,0,0,1,0,0,0,0,1,1,
1,1,0,0,1,0,1
    };
    int shipnodeshardamt[]={
0,1,1,0,0,1,0,0,0,1,1
,0,0,0,0,0,0,0,0,0,0,0,0,0,
1,1,1,1,0,0,1,1,0,0,0,0,1,0,1,
0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0
,0,1,1,1,1,0,0,1,0,1
    };
    float sshipshardamt[]={
4,0,0,4,4,0,4,0,4,0
,0,0.33,0,0.33,0,4,4,4,4,4,
4,4,0,0.33,0,0,0,0,4,4,0,0,4,4,
0,0,0,4,0,4,4,4,0,0,0,4,0,4,4,0,4,
4,0,4,4,4,0,0,0,0,0,4,4,0,4,0
    };
//length of the list
int length = sizeof(ships) / sizeof(ships[0]);

// Loop through the list and add character data to the string
for (int i = 0; i < length; i++) {
    std::string temp = "<option value=\"";
    temp += ships[i];
    temp += "\">";
    temp += ships[i];
    temp += "</option>\n";
    swgohMap += temp;
}
std::cout << swgohMap;
    return 0;
}

